---
title: "HOT-PET proxy: Ventricle volume (PF)"
output: html_notebook
---


```{r}
library(tidyverse)
library(readxl)
library(questionr)
library(ggpubr)
library(flextable)
library(reshape2)
library(ggmosaic)
library(psych)
library(scales)
library(vtable)
library(broom)
library(dotwhisker)

library(grid)
library(pROC)
library(plotROC)

load("NewData.RData") #DMT during the follow-up updated, ARR furing the follow-up added

Data2Decision1$EDSSch_group <- 0
Data2Decision1$EDSSch_group[which(is.na(Data2Decision1$EDSSchange))] <- NA
Data2Decision1$EDSSch_group[which(Data2Decision1$EDSSchange > 1)] <- 1
Data2Decision1$EDSSch_group[which(Data2Decision1$EDSSchange > 0.5 & Data2Decision1$EDSS >= 1 & Data2Decision1$EDSS < 6)] <- 1
Data2Decision1$EDSSch_group[which(Data2Decision1$EDSSchange > 0 & Data2Decision1$EDSS >= 6)] <- 1
Data2Decision1$EDSSch_group <- factor(Data2Decision1$EDSSch_group, levels = c(0, 1), labels = c("No progression", "Progression"))
Data2Decision1$EDSSch_group[Data2Decision1$EDSSnowDateDiff < 2] <- NA
#Data2Decision1$EDSSch_group[Data2Decision1$TreatmentDuringFollowUp == 2] <- NA


Data2 <- Data2Decision1 %>% filter(!is.na(EDSSch_group))
Data2$Total50 <- Data2$rimact_50 + Data2$overall_act_50 + Data2$inact_50
Data2$rBRLprop <- Data2$rBRLs/Data2$Total50*100

table(Data2$EDSSch_group)


Data2$ventrPFHigh <- Data2$ventrPF >= 2.12
Data2$HOTPET <- Data2$WMprop > 9.6
Data2$ventrPFHigh_HOTPET <- (Data2$ventrPF >= 2.12)*(Data2$WMprop > 9.6)
Data2$ventrPFHigh_AgeOld <- (Data2$ventrPF >= 2.12)*(Data2$Age >= 38.4)
Data2$ventrPFLow_THAvolHigh <- (Data2$ventrPF < 2.12)*(Data2$THAvolPF >= 1.02)
Data2$HighT1 <- Data2$T1load >= 7
Data2$ventrPFHigh_AgeOld_HighT1 <- (Data2$ventrPF >= 2.12)*(Data2$Age >= 38.4)*(Data2$T1load >= 7)



table(Data2$EDSSch_group, Data2$ventrPFHigh)
table(Data2$EDSSch_group, Data2$HOTPET)
table(Data2$EDSSch_group, Data2$ventrPFHigh_HOTPET)
table(Data2$EDSSch_group, Data2$ventrPFHigh_AgeOld)
table(Data2$EDSSch_group, Data2$ventrPFLow_THAvolHigh)
table(Data2$EDSSch_group, Data2$HighT1)
table(Data2$EDSSch_group, Data2$ventrPFHigh_AgeOld_HighT1)
table(Data2$EDSSch_group, Data2$Type)
table(Data2$EDSSch_group, Data2$EDSS > 4)


# Separate analyses for RRMS and PMS?
# High ventrPF vs. rBRL?


#Logistic regression assumptions:
#1. Binary response -> Yes
#2. Observations are independent -> Yes
#3. No multicollinearity -> check vif values when multiple predictors
#4. No extreme outliers: Check cook's distance / leverage plot!
#5. There is a linear relationship vetween the variable and the logit of y - check that at lest roughly linear, e.g. you can draw a straight line within the shaded area..
#6. Sample size is large enough... well this is out of our hands..
#7. No zero cells in contingency tables especially if interaction effects are tested -> does not apply here that much..


```


```{r fig.height=7, fig.width=8}
newlabels1 <- c("NAWM" = "NAWM DVR", "Thalamus" = "Thalamus DVR", "T1" = "T1 DVR", "T2" = "T2 DVR", "CorticalGM" = "Cortical GM DVR", "rim02mm" = "Rim DVR", "rim26mm" = "Perilesional DVR", "CAU" = "Caudate DVR", "Putamen" = "Putamen DVR", "PAL" = "Pallidum DVR",
                "NAWMprop" = "% of active voxels in NAWM", "ThaProp" = "% of active voxels in thalamus", "BRProp" = "% of active voxels in brain",
                #"rBRLprop" = "% of broad rim lesions (size 50+)",
                "rimact_pr" = "% of rim-active lesions", "overall_act_pr" = "% of overall-active lesions", "inact_pr" = "% of inactive lesions", "rimact_vol_pr" = "Volume % of rim-active lesions", "overall_act_vol_pr" = "Volume % of overall-active lesions", "inact_vol_pr" = "Volume % of inactive lesions",
                "all" = "Total number of T1 WM lesions",
                "BrainVolPF" = "Brain volume (PF)", "NAWMvolPF" = "NAWM volume (PF)", "GMctxVolPF" = "Cortical GM volume (PF)", "THAvolPF" = "Thalamus volume (PF)", "ventrPF" = "Ventricle volume (PF)", "ventr" = "Ventricle volume (cm^3)", "T1loadPF" = "T1 lesion load (PF)", "T2loadPF" = "T2 lesion load (PF)",
                "Age" = "Age", "Duration" = "Disease duration", "ARRbl" = "ARR", "EDSS" = "EDSS", "BMI" = "BMI", "Genderm" = "Sex: Male (vs. Female)", "TreatmentLevelBL2kkTRUE" = "DMT: Yes (vs. no)",
                "ventrPFHigh" = "Ventricle volume (PF) >= 2.12 (vs. not)", "HOTPET" = "HOT-PET: Yes (vs. not)", "ventrPFHigh_HOTPET" = "Ventricle volume >= 2.12 & HOT-PET (vs. not)", "ventrPFHigh_AgeOld" = "Ventricle volume >= 2.12 & Age >= 38.4 y (vs. not)", "ventrPFLow_THAvolHigh" = "Ventricle volume < 2.12 & Thalamus volume (PF) >= 1.02 (vs. not)") #"HIP" = "Hippocampus DVR", 

varlist1 <- c("NAWM", "Thalamus", "T1", "T2", "CorticalGM", "rim02mm", "rim26mm", "CAU", "Putamen", "PAL", "NAWMprop", "ThaProp", "BRProp", #"rBRLprop",
              "rimact_pr", "overall_act_pr", "inact_pr", "rimact_vol_pr", "overall_act_vol_pr", "inact_vol_pr", "all", "BrainVolPF", "NAWMvolPF", "GMctxVolPF", "THAvolPF", "ventrPF", "ventr", "T1loadPF", "T2loadPF", "Age", "Duration", "ARRbl", "EDSS", "BMI", "Gender", "TreatmentLevelBL2kk",
              "ventrPFHigh", "HOTPET", "ventrPFHigh_HOTPET", "ventrPFHigh_AgeOld", "ventrPFLow_THAvolHigh", "EDSSch_group") #, "HIP"

nvar <- length(varlist1) - 1 #Outcome and covariates not included
m1_df <- data.frame(matrix(NA, ncol = 8, nrow = nvar))
names(m1_df) <- c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high", "by_2sd")

Data3 <- Data2 %>% select(all_of(varlist1))

Data3$TreatmentLevelBL2kk <- Data3$TreatmentLevelBL2kk > 0

for(i in 1:nvar) {
  Data4 <- Data3
  name1 <- names(Data3)[i]
  names(Data4)[i] <- "Var"

  lol <- glm(EDSSch_group ~ Var, data = Data4, family = binomial(link = "logit"))
  df0 <- tidy(lol, conf.int = TRUE) 
  
  df0[2,1] <- name1
  if (name1 == "Gender") {
      df0[2,1] <- "Genderm"
  }
  if (name1 == "TreatmentLevelBL2kk") {
      df0[2,1]<- "TreatmentLevelBL2kkTRUE"
  }
  df1 <- df0 %>% by_2sd(Data3) #by_sd used for Forest plot 
  #df1 <- df0 #by_sd NOT used for Excel table -> Original estimates
  m1_df[i, ] <- df1[2, ]
  par(mfrow = c(2, 2))
  plot(lol) #Just for checking the influential values... None here!
  par(mfrow = c(1, 1))
  cat(name1, ":\n")
  cat("\n")
}

#ORs and confidence intervals for 0.1 an 1 unit increase
m1_df$OR1 <- exp(m1_df$estimate)
m1_df$OR01 <- exp(0.1*m1_df$estimate)

m1_df$OR1low <- exp(m1_df$conf.low)
m1_df$OR01low <- exp(0.1*m1_df$conf.low)

m1_df$OR1high <- exp(m1_df$conf.high)
m1_df$OR01high <- exp(0.1*m1_df$conf.high)

m1_df

m1_df$p.value <- round(m1_df$p.value, 3)
m1_df$p.value[m1_df$p.value >= 0.2] <- round(m1_df$p.value[m1_df$p.value >= 0.2], 1)
m1_df$p.value[which(m1_df$p.value >= 0.1 & m1_df$p.value <= 0.199)] <- round(m1_df$p.value[which(m1_df$p.value >= 0.1 & m1_df$p.value <= 0.199)], 2)
m1_df$p.value[m1_df$p.value < 0.001] <- "< 0.001"


d1 <- dwplot(m1_df, whisker_args = list(alpha = 0.75, size = 1.2, colour = "#44AA99"), dot_args = list(size = 1.4, colour = "#44AA99")) %>%
  relabel_predictors(newlabels1) +
  theme_bw() + xlab("Standardized logit") + ylab("") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2, size = 1.2) +
  theme(legend.position = "none") +
  theme(panel.spacing = unit(0, "lines")) +
  scale_x_continuous(breaks = c(-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10)) + 
  coord_cartesian(xlim = c(-3, 3), clip = "off") +
  theme(plot.margin = unit(c(6, 12, -0.9, 2), "mm"))
for(i in 1:nvar) {
  d1 <- d1 + annotation_custom(textGrob(label = m1_df$p.value[i], hjust = 0.5, gp = gpar(cex = 0.8)), xmin = 3.6, xmax = 3.6, ymin = nvar + 1 - i, ymax = nvar + 1 - i)
}
d1 <- d1 + annotation_custom(textGrob(label = expression(bold(p)), hjust = -1.5, gp = gpar(cex = 0.9)), xmin = 3.4, xmax = 3.4, ymin = nvar + 0.75, ymax = nvar + 0.75)
d1

ggsave("ForestPlot_univariate.tiff", units = "in", width = 8, height = 7, dpi = 300, compression = "lzw")
```


# Multivariate modelling: Without PET

```{r fig.height=6, fig.width=6}
lol1 <- glm(EDSSch_group ~ 1, family = "binomial", data = Data3)
lol2 <- MASS::stepAIC(lol1, scope = . ~ . + BrainVolPF + GMctxVolPF + THAvolPF + T1loadPF + T2loadPF + ventrPF + Age + Duration + ARRbl + EDSS + BMI + Gender + TreatmentLevelBL2kk, direction = "forward", trace = F, k = 2) #rim02mm +
#NAWMvolPF removed: high p-value in univariate models
car::vif(lol2)
summary(lol2)
plot(lol2)

#For each 0.1 increase in a variable, the odds of progression is..
#exp(0.1*coef(lol2)) #Equivalently: (exp(coef(lol2))^0.1)
exp(coef(lol2))

# Extract model results
model.data <- broom::augment(lol2) %>% mutate(index = 1:n()) 
model.data %>% top_n(3, .cooksd)

probabilities <- predict(lol2, type = "response")
predicted.classes <- ifelse(probabilities > 0.5, "pos", "neg")

# Select only numeric predictors
Dataaa <- Data3[c("EDSSch_group", "Duration", "BMI", "TreatmentLevelBL2kk")]
mydata <- Dataaa %>% dplyr::select_if(is.numeric)
predictors <- colnames(mydata)
# Bind the logit and tidying the data for plot
mydata <- mydata %>% mutate(logit = log(probabilities/(1 - probabilities))) %>% gather(key = "predictors", value = "predictor.value", -logit)
p1 <- ggplot(mydata, aes(logit, predictor.value)) + geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess") + theme_bw() + facet_wrap(~predictors, scales = "free_y")
plot(p1)

#Leave one out cross validation
fitted0 <- 0
for (i in 1:nrow(Dataaa)) {
    lolCV1 <- glm(lol2$formula, family = "binomial", data = Data3[-i, ])
    fitted0[i] <- predict(lolCV1, Data3[i, ], type = "response") #gives probability
}


fitted1 <- fitted0 > 0.5
tvl1 <- table(fitted1, Data3$EDSSch_group)
print(tvl1[2:1, 2:1])
colnames(tvl1) <- 0:1
rownames(tvl1) <- 0:1
tvl1


roc_obj <- roc(Data3$EDSSch_group, fitted0, ci = TRUE) #roc(response, predictor...

auc1 <- auc(roc_obj)

p1 <- pROC::ggroc(roc_obj, legacy.axes = TRUE, size = 1.5, ci = TRUE) #from pROC package
pROCa_AllMS <- p1 + #style_roc() +
  style_roc(xlab = "1 - Specificity", ylab = "Sensitivity") +
  theme(axis.title = element_text(size = 16, face = "bold"),
        axis.text = element_text(size = 16, face = "bold")) +
  theme(strip.text.x = element_text(size = 16)) +
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold")) +
  annotate(geom = "text", y = 0.375, x = 0.625, label = paste0("AUC = ", round(auc1, 2)), size = 5) #+
 # geom_ribbon(data = dat.ci, aes(x = x, ymin = lower, ymax = upper), fill = "steelblue", alpha = 0.2)
plot(pROCa_AllMS)

ci.auc(roc_obj, conf.level = 0.95)
```


# Multivariate modelling: With PET

```{r fig.height=6, fig.width=6}
lol1 <- glm(EDSSch_group ~ 1, family = "binomial", data = Data3)
lol2 <- MASS::stepAIC(lol1, scope = . ~ . + NAWM + rim26mm + Putamen + PAL + NAWMprop + BRProp + rimact_pr + overall_act_pr + inact_pr + rimact_vol_pr + inact_vol_pr + all + BrainVolPF + GMctxVolPF + THAvolPF + ventrPF + T1loadPF + T2loadPF + Duration + ARRbl + EDSS + BMI + Gender + TreatmentLevelBL2kk, direction = "forward", trace = F, k = 2)
#Imaging variables with high univariate p-value removed: Thalamus + T1 + CorticalGM + CAU + ThaProp + overall_act_vol_pr + NAWMvolPF
shapiro.test(lol2$residuals)
car::vif(lol2) #high vifs in the model: removed rim02mm, Age (compared to Duration)
summary(lol2)
plot(lol2)

fitted1 <- fitted(lol2) > 0.5
table(Data3$EDSSch_group, fitted1)

exp(coef(lol2)) #Equivalently: (exp(coef(lol2))^0.1)

#For each 0.1 increase in a variable, the odds of progression increases by..
exp(0.1*coef(lol2)) #Equivalently: (exp(coef(lol2))^0.1)

# Extract model results
model.data <- broom::augment(lol2) %>% mutate(index = 1:n()) 
model.data %>% top_n(3, .cooksd)

probabilities <- predict(lol2, type = "response")
predicted.classes <- ifelse(probabilities > 0.5, "pos", "neg")

# Select only numeric predictors
Dataaa <- Data3[c("EDSSch_group", "rim26mm", "Duration", "TreatmentLevelBL2kk")]
mydata <- Dataaa %>% dplyr::select_if(is.numeric)
predictors <- colnames(mydata)
# Bind the logit and tidying the data for plot
mydata <- mydata %>% mutate(logit = log(probabilities/(1 - probabilities))) %>% gather(key = "predictors", value = "predictor.value", -logit)
p1 <- ggplot(mydata, aes(logit, predictor.value)) + geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess") + theme_bw() + facet_wrap(~predictors, scales = "free_y")
plot(p1)

#Leave one out cross validation
fitted0 <- 0
for (i in 1:nrow(Dataaa)) {
    lolCV1 <- glm(lol2$formula, family = "binomial", data = Data3[-i, ])
    fitted0[i] <- predict(lolCV1, Data3[i, ], type = "response") #gives probability
}

fitted1 <- fitted0 > 0.5
tvl1 <- table(fitted1, Data3$EDSSch_group)
print(tvl1[2:1, 2:1])
colnames(tvl1) <- 0:1
rownames(tvl1) <- 0:1
tvl1

roc_obj <- roc(Data3$EDSSch_group, fitted0, ci = TRUE) #roc(response, predictor...

auc1 <- auc(roc_obj)

p1 <- pROC::ggroc(roc_obj, legacy.axes = TRUE, size = 1.5, ci = TRUE) #from pROC package
pROCa_AllMS <- p1 + #style_roc() +
  style_roc(xlab = "1 - Specificity", ylab = "Sensitivity") +
  theme(axis.title = element_text(size = 16, face = "bold"),
        axis.text = element_text(size = 16, face = "bold")) +
  theme(strip.text.x = element_text(size = 16)) +
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold")) +
  annotate(geom = "text", y = 0.375, x = 0.625, label = paste0("AUC = ", round(auc1, 2)), size = 5) #+
 # geom_ribbon(data = dat.ci, aes(x = x, ymin = lower, ymax = upper), fill = "steelblue", alpha = 0.2)
plot(pROCa_AllMS)

ci.auc(roc_obj, conf.level = 0.95)



```

```{r}
HOTPETdata <- Data2 %>% filter(HOTPET == TRUE)

table(HOTPETdata$ventrPF > 2.12)

```

